import ART1 from "../assets/arts/starwars.png";
import ART2 from "../assets/arts/ZOOM_INTERVIEW.png";
import ART3 from "../assets/arts/Inked.png";
import ART4 from "../assets/arts/Inkedhook2.jpg";
import ART5 from "../assets/arts/junpradox.png";
import ART6 from "../assets/arts/new_art/1.jpeg";
import ART7 from "../assets/arts/new_art/2.jpeg";
import ART8 from "../assets/arts/new_art/3.jpeg";
import ART9 from "../assets/arts/new_art/4.jpeg";
import ART10 from "../assets/arts/new_art/5.jpeg";
import ART11 from "../assets/arts/new_art/6.jpeg";
import ART12 from "../assets/arts/new_art/7.jpeg";
import ART13 from "../assets/arts/new_art/8.jpeg";
import ART14 from "../assets/arts/new_art/9.jpeg";
import ART15 from "../assets/arts/new_art/10.jpeg";
import ART16 from "../assets/arts/new_art/11.jpeg";
import ART17 from "../assets/arts/new_art/12.jpeg";
import ART18 from "../assets/arts/new_art/13.jpeg";
import ART19 from "../assets/arts/new_art/14.jpeg";
import ART20 from "../assets/arts/new_art/15.jpeg";
import ART21 from "../assets/arts/new_art/16.jpeg";
import ART22 from "../assets/arts/new_art/17.jpeg";
import ART23 from "../assets/arts/new_art/18.jpeg";
import ART24 from "../assets/arts/new_art/19.jpeg";
import ART25 from "../assets/arts/new_art/20.jpeg";
import ART26 from "../assets/arts/new_art/father_daוghter.png";
import ART27 from "../assets/arts/new_art/father_kids.jpg";

const imageStock = [
  { url: ART1 },
  { url: ART2 },
  { url: ART3 },
  { url: ART4 },
  { url: ART5 },
  { url: ART6 },
  { url: ART7 },
  { url: ART8 },
  { url: ART9 },
  { url: ART10 },
  { url: ART11 },
  { url: ART12 },
  { url: ART13 },
  { url: ART14 },
  { url: ART15 },
  { url: ART16 },
  { url: ART17 },
  { url: ART18 },
  { url: ART19 },
  { url: ART20 },
  { url: ART21 },
  { url: ART22 },
  { url: ART23 },
  { url: ART24 },
  { url: ART25 },
  { url: ART26 },
  { url: ART27 },
];
export default imageStock;
